import type { Metadata } from "next";
import Nav from "./components/Nav";
import Form from "./components/Form";
import Footer from "./components/Footer";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
    robots: {
        index: false,
        follow: false,
        nocache: true,
        googleBot: {
            index: false,
            follow: false,
            noimageindex: true,
            "max-video-preview": -1,
            "max-image-preview": "large",
            "max-snippet": -1,
        },
    },
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body>
                <Nav />
                {children}
                <Form />
                <Footer />
            </body>
        </html>
    );
}
